### ISSUE TITLE
Game crashes when placing a hopper above a kiln

### ISSUE THREAD

**Issue by MikroChris** [Axanthic-Game-Studios/Lands-of-Icaria#15]
Hi, I was trying to automatize a loam brick smelting, but when I placed the hopper above the kiln and put the loam in it, it crashed the game :c

**Comment by luxtracon** [comment]
Hey! Sorry for the inconvenience. I just double checked if it crashes for me too but it does work just fine, see the screenshot attached. Besides that, the input for the material for the Kiln is indicated by the dark metal-like piece on its upper left, the input for the fuel by the part on the lower back. But still, even if a player might misplaced a hopper on the top, it sure shouldn't crash. Could you supply me with a crash report, so I could have a deeper look into it to maybe fix the issue?

![image](https://github.com/Axanthic-Game-Studios/Lands-of-Icaria/assets/58708938/490567d1-4899-43f3-8644-28a989272011)

**Comment by MikroChris** [comment]
Hmm, you're right, It isn't happening anymore, I don't know what was it then ;c
Thank you very much for your support!

**Comment by luxtracon** [comment]
If the issue or any other issues occur again, don't hesitate to let us know.

**Comment by MikroChris** [comment]
Thank You, really appreciate that!
Also, I really like your mod, it's so good
