### ISSUE TITLE
Crash when hovering over some items of icaria tab or scroll down too

### ISSUE THREAD

**Issue by X-Machiavelli** [Axanthic-Game-Studios/Lands-of-Icaria#17]
The launcher loads normally. However, the problem arises when looking at icaria's item in the UI with CreativeMode. The problem persists even when I disable all other mods. These are my specifications.

environment: client or server both
neoforge21.1.54, MC1.21.1
mod: Icaria 1.21 2.2.3.0
[crash-2024-09-16_23.30.57-client.txt](https://github.com/user-attachments/files/17014897/crash-2024-09-16_23.30.57-client.txt)
[latest.log](https://github.com/user-attachments/files/17014901/latest.log)

I hope this issue can be improved. thank you for your service.

**Comment by luxtracon** [comment]
Hey, it seems you are using the latest version of Icaria for Minecraft 1.21.1. Our latest version is not yet compatible for the latest Minecraft version. There is a reason it is not marked as compatible with that version on our download pages yet and only with 1.21. We are currently in the middle of preparing our next update, which will be released for 1.21.1.

**Comment by luxtracon** [comment]
c5231c0 fixes this, update will be out soon
