### ISSUE TITLE
extreme lag when viewing blocks from this mod with jei

### ISSUE THREAD

**Issue by VaporeonScripts** [Axanthic-Game-Studios/Lands-of-Icaria#19]
![image](https://github.com/user-attachments/assets/aff1b875-b764-46b7-90ad-08846d74d846)
neoforge 1.21.1 .80

**Comment by luxtracon** [comment]
What version of JEI are you using?

**Comment by VaporeonScripts** [comment]
latest

**Comment by luxtracon** [comment]
I'm trying to reproduce the issue, with no success so far. Does it only appear when hovering over specific items or in general when any of the items is displayed without hovering over it? Are you using any other mods in addition (it's seems like it, telling by the screenshot). Could you supply a full modlist or even better the latest game log file?

**Comment by VaporeonScripts** [comment]
https://mclo.gs/JvtKc8k

**Comment by VaporeonScripts** [comment]
it happens when i search it? ig

**Comment by VaporeonScripts** [comment]
lemme get a full one

**Comment by VaporeonScripts** [comment]
https://mclo.gs/XCnyDg0

**Comment by luxtracon** [comment]
Thanks. Icaria isn't even installed in this profile tho. I assume you just removed it? 549 is quite a lot of mods to try to figure out if there might be any cross compatibility issues. Does it also happen if you only use JEI and Icaria together, without any other mods? Are you playing on a server? How could you best describe the observed lags? Does the framerate drop?

**Comment by VaporeonScripts** [comment]
the fps drop fixed itself after closing and opening jei multiple times somehow, could be related to my machine

**Comment by luxtracon** [comment]
Unusual behaviour nonetheless, let me know if it happens again. I could observe a slightly dropping framrate when displaying some of our more detailed block-item models (like the Forge multiblock, Triple Barrel Rack multiblock, etc). Obviously these models will drop the framerate to an extend when displayed compared to plain blocks. On some weaker machines this effect might be more noticeable.
