### ISSUE TITLE
Duplicate ID or something.

### ISSUE THREAD

**Issue by dazadazu** [Axanthic-Game-Studios/Lands-of-Icaria#4]
[crash-2021-04-13_19.57.05-client.txt](https://github.com/Axanthic-Game-Studios/Lands-of-Icaria/files/6307929/crash-2021-04-13_19.57.05-client.txt)

**Comment by RCXcrafter** [comment]
You've already reported this crash and I've already fixed it, if you update to the latest version it shouldn't happen anymore.
