### ISSUE TITLE
Crash with Buildcraft [1.0.3 Beta Preview]

### ISSUE THREAD

**Issue by aking4125** [Axanthic-Game-Studios/Lands-of-Icaria#5]
Hey!

Just found out about this mod and looked pretty cool, wanted to give it a shot so I added it to my personal pack that I'm developing for my family. Sadly, we're getting this crash that is reportedly related to Buildcraft. Removing this mod or Buildcraft fixes the issue.

This issue occurs only with the 1.0.3 Beta Preview build from Curseforge. 1.0.2 seems to work fine. I understand that build is intended as only a preview but wanted to at least report that in case. Just a note as something seemed to have changed.

[crash-2021-08-20_09.43.30-client.txt](https://github.com/Axanthic-Game-Studios/Lands-of-Icaria/files/7021982/crash-2021-08-20_09.43.30-client.txt)

Just in case, [this is the version of buildcraft we are using.](https://www.curseforge.com/minecraft/mc-mods/buildcraft/files/3204475)

**Comment by RCXcrafter** [comment]
This seems to be a bug with buildcraft, I'll report it to them.

**Comment by AlexIIL** [comment]
This also happens if I use the command `/give AlexIIl landsoficaria:rock 1 26` with the 1.0.3  beta preview - so I don't think this is buildcraft's fault, and a check for invalid metadata should probably happen on Lands of Icaria's side.

**Comment by RCXcrafter** [comment]
Will be fixed on our side in the next released version.
https://github.com/Axanthic-Game-Studios/Lands-of-Icaria/commit/40494be69ef2bea02302f1e2daee3dfef95f8141
